// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBot.api.Data;

#nullable disable

namespace TelegramBot.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510005335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TelegramBot.api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кофе"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Десерты"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Напитки"
                        });
                });

            modelBuilder.Entity("TelegramBot.api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Капучино",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Латте",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Чизкейк",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Тирамису",
                            Price = 2100m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Лимонад",
                            Price = 900m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Чай Ташкентский",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("TelegramBot.api.Models.Product", b =>
                {
                    b.HasOne("TelegramBot.api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TelegramBot.api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
